package controller;

public enum Events {
	
	ADD_PROCESS,UPDATE_PROCESS,DELETE_PROCESS,SIMULATE_PROCESS,SHOW_PROCESS_ADD, ALERTA_VOLVER,
	CONFIRM_ADD_PROCESS,RETURN_MAIN_MENU, SEARCH_LIST_PROCESS, RESET_SIMULATION, GO_BACK_MENU_SIMULATION,EXIT,COMUNICATE_PROCESS,
	ACCEPT_COMUNICATION,CHANGUE_PRIORITY_PROCESS,CONFIRM_CHANGUE_PRIORITY
	

}
